version: '3'

vars:
  NAME: main
  BIN: sys-fetch
  CROSS_ARM64: aarch64-linux-gnu-

tasks:
  clean:
    desc: Remove all build artifacts and intermediate files
    cmds:
      - rm -rf bin/
      - rm -f src/x86_64/*.o
      - rm -f src/aarch64/*.o
      - rm -f ref/rosetta-amd64 ref/rosetta-amd64.s

  deps:amd64:
    desc: Install build dependencies for amd64 (x86_64)
    cmds:
      - sudo apt update
      - sudo apt install -y binutils build-essential gdb

  deps:arm64:
    desc: Install build dependencies for arm64 (aarch64)
    cmds:
      - sudo apt update
      - sudo apt install -y binutils-aarch64-linux-gnu build-essential gdb

  # ---------------------------------------------------------------------------
  # amd64 (x86_64) Tasks
  # ---------------------------------------------------------------------------

  assy:amd64:
    desc: Assemble the amd64 source code into an object file
    preconditions:
      - sh: command -v as > /dev/null
        msg: "The GNU Assembler (as) is not installed. Please install it with 'sudo apt install binutils'."
    dir: src/x86_64
    cmds:
      - as {{.NAME}}.S -o {{.NAME}}.o

  link:amd64:
    desc: Link the amd64 object file into the final executable
    preconditions:
      - sh: command -v ld > /dev/null
        msg: "The GNU Linker (ld) is not installed. Please install it with 'sudo apt install binutils'."
    cmds:
      - mkdir -p bin/x86_64
      - ld src/x86_64/{{.NAME}}.o -o bin/x86_64/{{.BIN}}

  build:amd64:
    desc: Assemble and link the amd64 tool
    cmds:
      - task: assy:amd64
      - task: link:amd64

  run:amd64:
    desc: Execute the amd64 binary
    cmds:
      - ./bin/x86_64/{{.BIN}}

  inspect:bin:amd64:
    desc: Disassemble the amd64 binary using objdump
    preconditions:
      - sh: command -v objdump > /dev/null
        msg: "objdump is not installed. Please install it with 'sudo apt install binutils'."
    cmds:
      - objdump -d bin/x86_64/{{.BIN}}

  inspect:obj:amd64:
    desc: Disassemble the amd64 object file using objdump
    preconditions:
      - sh: command -v objdump > /dev/null
        msg: "objdump is not installed. Please install it with 'sudo apt install binutils'."
    cmds:
      - objdump -d src/x86_64/{{.NAME}}.o

  strace:amd64:
    desc: Trace system calls of the amd64 binary using strace
    preconditions:
      - sh: command -v strace > /dev/null
        msg: "strace is not installed. Please install it with 'sudo apt install strace'."
    cmds:
      - strace ./bin/x86_64/{{.BIN}}

  build-run:amd64:
    desc: Build and run the amd64 tool
    cmds:
      - task: build:amd64
      - task: run:amd64

  dbg:amd64:
    desc: Build with debug symbols and start GDB for amd64
    preconditions:
      - sh: command -v as > /dev/null
        msg: "The GNU Assembler (as) is not installed. Please install it with 'sudo apt install binutils'."
      - sh: command -v ld > /dev/null
        msg: "The GNU Linker (ld) is not installed. Please install it with 'sudo apt install binutils'."
      - sh: command -v gdb > /dev/null
        msg: "GDB is not installed. Please install it with 'sudo apt install gdb'."
    cmds:
      - mkdir -p bin/x86_64
      - as -g src/x86_64/{{.NAME}}.S -o src/x86_64/{{.NAME}}.o
      - ld src/x86_64/{{.NAME}}.o -o bin/x86_64/{{.BIN}}
      - gdb bin/x86_64/{{.BIN}}

  # ---------------------------------------------------------------------------
  # arm64 (aarch64) Tasks
  # ---------------------------------------------------------------------------

  assy:arm64:
    desc: Assemble the arm64 source code into an object file
    preconditions:
      - sh: command -v {{.CROSS_ARM64}}as > /dev/null
        msg: "The ARM64 GNU Assembler is not installed. Please install it with 'task deps:arm64'."
    dir: src/aarch64
    cmds:
      - "{{.CROSS_ARM64}}as {{.NAME}}.S -o {{.NAME}}.o"

  link:arm64:
    desc: Link the arm64 object file into the final executable
    preconditions:
      - sh: command -v {{.CROSS_ARM64}}ld > /dev/null
        msg: "The ARM64 GNU Linker is not installed. Please install it with 'task deps:arm64'."
    cmds:
      - mkdir -p bin/aarch64
      - "{{.CROSS_ARM64}}ld src/aarch64/{{.NAME}}.o -o bin/aarch64/{{.BIN}}"

  build:arm64:
    desc: Assemble and link the arm64 tool
    cmds:
      - task: assy:arm64
      - task: link:arm64

  run:arm64:
    desc: Execute the arm64 binary
    preconditions:
      - sh: uname -m | grep -q aarch64 || command -v qemu-aarch64 > /dev/null
        msg: "You are not on an ARM64 host. Please install 'qemu-user' to run ARM64 binaries."
    cmds:
      - "uname -m | grep -q aarch64 && ./bin/aarch64/{{.BIN}} || qemu-aarch64 ./bin/aarch64/{{.BIN}}"

  inspect:bin:arm64:
    desc: Disassemble the arm64 binary using objdump
    preconditions:
      - sh: command -v {{.CROSS_ARM64}}objdump > /dev/null
        msg: "ARM64 objdump is not installed. Please install it with 'task deps:arm64'."
    cmds:
      - "{{.CROSS_ARM64}}objdump -d bin/aarch64/{{.BIN}}"

  inspect:obj:arm64:
    desc: Disassemble the arm64 object file using objdump
    preconditions:
      - sh: command -v {{.CROSS_ARM64}}objdump > /dev/null
        msg: "ARM64 objdump is not installed. Please install it with 'task deps:arm64'."
    cmds:
      - "{{.CROSS_ARM64}}objdump -d src/aarch64/{{.NAME}}.o"

  strace:arm64:
    desc: Trace system calls of the arm64 binary using strace
    preconditions:
      - sh: uname -m | grep -q aarch64
        msg: "strace for ARM64 only works on an ARM64 host."
    cmds:
      - strace ./bin/aarch64/{{.BIN}}

  build-run:arm64:
    desc: Build and run the arm64 tool
    cmds:
      - task: build:arm64
      - task: run:arm64

  # ---------------------------------------------------------------------------
  # Rosetta Reference & Utility Tasks
  # ---------------------------------------------------------------------------

  rosetta-amd64:
    desc: Compile and generate assembly listing for the C reference implementation
    preconditions:
      - sh: command -v gcc > /dev/null
        msg: "GCC is not installed. Please install it with 'sudo apt install build-essential'."
    dir: ref
    cmds:
      - gcc -o rosetta-amd64 rosetta.c
      - gcc -S -o rosetta-amd64.s rosetta.c

  view-rosetta-asm:
    desc: Display the generated assembly for the C reference implementation
    preconditions:
      - sh: test -f ref/rosetta-amd64.s
        msg: "Run 'task rosetta-amd64' first to generate the assembly listing."
    cmds:
      - command -v bat > /dev/null && bat ref/rosetta-amd64.s || cat ref/rosetta-amd64.s

  default:
    desc: List all available tasks
    cmds:
      - task -l
    silent: true
