version: '3'

vars:
  NAME: main
  BIN: sys-fetch

tasks:
  clean:
    desc: Remove all build artifacts and intermediate files
    cmds:
      - rm -rf bin/{{.BIN}}
      - rm -f src/x86_64/*.o
      - rm -f ref/rosetta-amd64 ref/rosetta-amd64.s

  deps:amd64:
    desc: Install build dependencies for amd64 (x86_64)
    cmds:
      - sudo apt update
      - sudo apt install -y binutils build-essential gdb

  deps:arm64:
    desc: Install build dependencies for arm64 (aarch64)
    cmds:
      - sudo apt update
      - sudo apt install -y binutils-aarch64-linux-gnu build-essential gdb

  assy:amd64:
    desc: Assemble the amd64 source code into an object file
    dir: src/x86_64
    cmds:
      - as {{.NAME}}.S -o {{.NAME}}.o

  link:amd64:
    desc: Link the amd64 object file into the final executable
    cmds:
      - mkdir -p bin
      - ld src/x86_64/{{.NAME}}.o -o bin/{{.BIN}}

  build:amd64:
    desc: Assemble and link the amd64 tool
    cmds:
      - task: assy:amd64
      - task: link:amd64

  run:amd64:
    desc: Execute the amd64 binary
    cmds:
      - ./bin/{{.BIN}}

  build-run:
    desc: Build and run the amd64 tool
    cmds:
      - task: build:amd64
      - task: run:amd64

  dbg:amd64:
    desc: Build with debug symbols and start GDB for amd64
    cmds:
      - mkdir -p bin
      - as -g src/x86_64/{{.NAME}}.S -o src/x86_64/{{.NAME}}.o
      - ld src/x86_64/{{.NAME}}.o -o bin/{{.BIN}}
      - gdb bin/{{.BIN}}

  rosetta-amd64:
    desc: Compile and generate assembly listing for the C reference implementation
    dir: ref
    cmds:
      - gcc -o rosetta-amd64 rosetta.c
      - gcc -S -o rosetta-amd64.s rosetta.c

  view-rosetta-asm:
    desc: Display the generated assembly for the C reference implementation
    preconditions:
      - sh: test -f ref/rosetta-amd64.s
        msg: "Run 'task rosetta-amd64' first to generate the assembly listing."
    cmds:
      - command -v bat > /dev/null && bat ref/rosetta-amd64.s || cat ref/rosetta-amd64.s

  default:
    desc: List all available tasks
    cmds:
      - task -l
    silent: true
